import { getServerSession } from 'next-auth'
import './globals.css'
import { Inter } from 'next/font/google'
import { authOptions } from '../lib/auth'
import { NextAuthProvider } from './providers'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
            <body>
                <NextAuthProvider>{children}</NextAuthProvider>
            </body>
        </html>
    )
}
