'use client'

import { getServerSession } from 'next-auth'
import './globals.css'
import { Inter } from 'next/font/google'
import { NextAuthProvider } from './providers'
import { RecoilRoot } from 'recoil';


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//     title: '김상민',
//     description: 'Generated by create next app',
//     icons: {
//         icon: '/favicon.ico',
//     }
// }

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
            <body>
                {/* 만든 Provider로 자식 컴포넌트 감싸 모든 컴포넌트 guard를 담당합니다.*/}
                <NextAuthProvider>
                    {/* Recoil 상태관리 라이브러리 */}
                    <RecoilRoot>
                        {children}
                    </RecoilRoot>
                </NextAuthProvider>
            </body>
        </html>
    )
}
